"""Apply the shared biome tuning to engine defaults and plan's scatter rules.

Only five scatter slots change; terrain, grass, detail rings, roads and world
entities retain their existing data. Run after building the model exports.
"""
import argparse
import json
from pathlib import Path
import re
import shutil
import xml.etree.ElementTree as ET

ROOT=Path(__file__).resolve().parents[2]
CONFIG=Path(__file__).with_name('biome_layers.json')
PATH='project/models/island_biomes/{0}/{0}.gltf'

def main(apply):
    config=json.loads(CONFIG.read_text())
    cpp=['// Generated by tools/terrain_tests/author_island_biomes.py from biome_layers.json.',
         '// Copyright(c) 2015-2026 Panos Karabelas. Licensed under the MIT license.',
         '#pragma once','namespace spartan {',
         'inline void ApplyIslandScatterDefaults(std::array<TerrainScatterLayer, terrain_scatter_max>& layers)', '{']
    world=ROOT/'worlds/plan.world';text=world.read_text(encoding='utf-8');root=ET.fromstring(text)
    scatter=root.find('.//terrain/scatter')
    # Full defaults of an empty Mesh layer, preserving the XML schema.
    defaults=dict(name='',mesh_path='',mesh_variants='',habitat=0,enabled=False,kind=0,mountain_rocks=False,
        formation_spacing=300,formation_length=300,formation_width=130,formation_height=90,formation_jitter=15,
        embed_fraction=.45,coating=0,coating_scale=3,density=8,max_per_tile=0,seed=0,slope_min=0,slope_max=35,slope_bias=0,
        height_min=1,height_max=100000,height_fade=0,curvature=0,flow=0,occlusion=0,insolation=0,wear=0,deposition=0,talus=0,
        ground_mask=0,mask_channel=-1,mask_min=0,clump_radius=0,clump_count=1,clump_raggedness=1,clump_coverage=0,clump_invert=False,
        mesh_scale=1,size_min=.8,size_max=1.2,size_from_slope=0,size_from_altitude=0,altitude_span=180,giant_chance=0,giant_size=0,
        align_to_normal=1,surface_offset=.05,sink=0,blend_height=1,blend_sharpness=.5,render_distance=0,shadow_distance=150)
    integer={'habitat','max_per_tile','seed','ground_mask','mask_channel','clump_count','flags'}
    for key,setting in config.items():
        rule=dict(setting);assets=rule.pop('assets');rule['mesh_path']=PATH.format(assets[0]);rule['mesh_variants']=';'.join(PATH.format(a) for a in assets[1:])
        for asset in assets:assert (ROOT/'binaries'/PATH.format(asset)).exists(),asset
        cpp+=['    {',f'        auto& s = layers[{key}];','        s = TerrainScatterLayer{};']
        for field,value in rule.items():
            member=field+'_influence' if field in ['curvature','flow','occlusion','insolation','wear','deposition','talus'] else field
            literal=json.dumps(value) if isinstance(value,(str,bool)) else str(value) if field in integer else f'{float(value)}f'
            cpp.append(f'        s.{member} = {literal};')
        cpp+=['    }']
        values=dict(defaults,**rule)
        e=scatter[int(key)]
        # Keep ring settings for consistency even though these layers use mesh placement.
        for field,value in values.items():e.set(field,str(value).lower() if isinstance(value,bool) else str(value))
    cpp+=['}','}','']
    header=ROOT/'source/world/IslandScatterDefaults.h'
    header.write_text('\n'.join(cpp),encoding='utf-8')
    block=ET.tostring(scatter,encoding='unicode').strip()
    updated=re.sub(r'<scatter>.*?</scatter>',lambda _:block,text,count=1,flags=re.S)
    old=ET.fromstring(text);new=ET.fromstring(updated)
    for r in [old,new]:
        terrain=r.find('.//terrain');terrain.remove(terrain.find('scatter'))
    assert ET.tostring(old)==ET.tostring(new),'Changed data outside scatter'
    if apply:
        backup=ROOT/'binaries/project/backups/plan_before_biomes.world'
        backup.parent.mkdir(parents=True,exist_ok=True)
        if not backup.exists():shutil.copy2(world,backup)
        world.write_text(updated,encoding='utf-8',newline='\n')
    print(f'Generated shared engine defaults; island applied={apply}, {len(config)} layers, grass/flowers/pebbles unchanged')

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--apply',action='store_true');main(parser.parse_args().apply)
